In [1]:
import nltk

/opt/anaconda3/lib/python3.12/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/anaconda3/lib/python3.12/site-packages/pandas/core/arrays/masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [3]:
corpus = '''Machine learning is a subset of Artificial Intelligence (AI) that enables computers to learn from data and make predictions without being explicitly programmed. If you're new to this field, this tutorial will provide a comprehensive understanding of machine learning,its types, algorithms, tools, and practical applications.'''

In [5]:
corpus

"Machine learning is a subset of Artificial Intelligence (AI) that enables computers to learn from data and make predictions without being explicitly programmed. If you're new to this field, this tutorial will provide a comprehensive understanding of machine learning,its types, algorithms, tools, and practical applications."

In [7]:
corpus.split('.')

['Machine learning is a subset of Artificial Intelligence (AI) that enables computers to learn from data and make predictions without being explicitly programmed',
 " If you're new to this field, this tutorial will provide a comprehensive understanding of machine learning,its types, algorithms, tools, and practical applications",
 '']

## Sentence tokenization

In [10]:
from nltk import sent_tokenize,word_tokenize

In [14]:
sent_tok = sent_tokenize(corpus)

In [16]:
sent_tok

['Machine learning is a subset of Artificial Intelligence (AI) that enables computers to learn from data and make predictions without being explicitly programmed.',
 "If you're new to this field, this tutorial will provide a comprehensive understanding of machine learning,its types, algorithms, tools, and practical applications."]

In [18]:
len(sent_tok)

2

In [20]:
sent_tok[0]

'Machine learning is a subset of Artificial Intelligence (AI) that enables computers to learn from data and make predictions without being explicitly programmed.'

In [22]:
sent_tok[1]

"If you're new to this field, this tutorial will provide a comprehensive understanding of machine learning,its types, algorithms, tools, and practical applications."

In [24]:
ls = ["aa","bb","cc"]

In [26]:
"".join(ls)

'aabbcc'

In [28]:
" ".join(ls)

'aa bb cc'

In [30]:
". ".join(ls)

'aa. bb. cc'

In [32]:
"_".join(ls)

'aa_bb_cc'

In [34]:
" ".join(sent_tok)

"Machine learning is a subset of Artificial Intelligence (AI) that enables computers to learn from data and make predictions without being explicitly programmed. If you're new to this field, this tutorial will provide a comprehensive understanding of machine learning,its types, algorithms, tools, and practical applications."

## word tokenization

In [37]:
word_tokens = word_tokenize(corpus)

In [41]:
print(word_tokens)

['Machine', 'learning', 'is', 'a', 'subset', 'of', 'Artificial', 'Intelligence', '(', 'AI', ')', 'that', 'enables', 'computers', 'to', 'learn', 'from', 'data', 'and', 'make', 'predictions', 'without', 'being', 'explicitly', 'programmed', '.', 'If', 'you', "'re", 'new', 'to', 'this', 'field', ',', 'this', 'tutorial', 'will', 'provide', 'a', 'comprehensive', 'understanding', 'of', 'machine', 'learning', ',', 'its', 'types', ',', 'algorithms', ',', 'tools', ',', 'and', 'practical', 'applications', '.']

In [43]:
" ".join(word_tokens)

"Machine learning is a subset of Artificial Intelligence ( AI ) that enables computers to learn from data and make predictions without being explicitly programmed . If you 're new to this field , this tutorial will provide a comprehensive understanding of machine learning , its types , algorithms , tools , and practical applications ."

## Stemming and Lemmatization

#### Stemming

In [47]:
from nltk.stem import PorterStemmer

In [49]:
ps = PorterStemmer()

In [51]:
ps.stem("prediction")

'predict'

In [53]:
ps.stem("learning")

'learn'

In [55]:
ps.stem("Intelligence")

'intellig'

In [57]:
for word in word_tokens:
    stem_word = ps.stem(word)
    print(word,"-->",stem_word)

Machine --> machin
learning --> learn
is --> is
a --> a
subset --> subset
of --> of
Artificial --> artifici
Intelligence --> intellig
( --> (
AI --> ai
) --> )
that --> that
enables --> enabl
computers --> comput
to --> to
learn --> learn
from --> from
data --> data
and --> and
make --> make
predictions --> predict
without --> without
being --> be
explicitly --> explicitli
programmed --> program
. --> .
If --> if
you --> you
're --> 're
new --> new
to --> to
this --> thi
field --> field
, --> ,
this --> thi
tutorial --> tutori
will --> will
provide --> provid
a --> a
comprehensive --> comprehens
understanding --> understand
of --> of
machine --> machin
learning --> learn
, --> ,
its --> it
types --> type
, --> ,
algorithms --> algorithm
, --> ,
tools --> tool
, --> ,
and --> and
practical --> practic
applications --> applic
. --> .

#### Lemmatization

pos: The Part Of Speech tag. Valid options are `"n"` for nouns,
            `"v"` for verbs, `"a"` for adjectives, `"r"` for adverbs and `"s"`
            for satellite adjectives.

In [60]:
from nltk.stem import WordNetLemmatizer

In [62]:
lm = WordNetLemmatizer()

In [66]:
lm.lemmatize("Intelligence")

'Intelligence'

In [68]:
lm.lemmatize("prediction",pos="n")

'prediction'

In [72]:
lm.lemmatize("predicted",pos="v")

'predict'

In [78]:
for word in word_tokens:
    lemma_word = lm.lemmatize(word)
    print(word,"-->",lemma_word)

Machine --> Machine
learning --> learning
is --> is
a --> a
subset --> subset
of --> of
Artificial --> Artificial
Intelligence --> Intelligence
( --> (
AI --> AI
) --> )
that --> that
enables --> enables
computers --> computer
to --> to
learn --> learn
from --> from
data --> data
and --> and
make --> make
predictions --> prediction
without --> without
being --> being
explicitly --> explicitly
programmed --> programmed
. --> .
If --> If
you --> you
're --> 're
new --> new
to --> to
this --> this
field --> field
, --> ,
this --> this
tutorial --> tutorial
will --> will
provide --> provide
a --> a
comprehensive --> comprehensive
understanding --> understanding
of --> of
machine --> machine
learning --> learning
, --> ,
its --> it
types --> type
, --> ,
algorithms --> algorithm
, --> ,
tools --> tool
, --> ,
and --> and
practical --> practical
applications --> application
. --> .

## Text processing -- stopwords in NLTK

In [81]:
from nltk.corpus import stopwords

In [83]:
print(stopwords.words())

['tyre', 'rreth', 'le', 'atyre', 'këta', 'megjithëse', 'kemi', 'per', 'ndonëse', 'dytë', 'pse', 'tha', 'aty', 'ndaj', 'ke', 'këtë', 'duhet', 'pa', 'perket', 'veç', 'ndonje', 'një', 'keshtu', 's', 'janë', 'jane', 'ti', 'ia', 'megjithese', 'prej', 'ishte', 'tjerë', 'ai', 'se', 'tillë', 'do', 'si', 'ja', 'tonë', 'keta', 'pastaj', 'ndersa', 'siç', 'unë', 'gjate', 'di', 'kësaj', 'cilin', 'kjo', 'dhënë', 'da', 'teper', 'ketij', 'ama', 'pasi', 'fjalë', 'kanë', 'vetem', 'za', 'd.m.th.', 'ose', 'pas', 'ndonjë', 'cila', 'ndodhur', 'dyte', 'ardhur', 'kësi', 'nga', 'vete', 'atij', 'ta', 'jenë', 'rendit', 'tane', 'keso', 'deri', 'tone', 'të', 'prandaj', 'bëjë', 'domethënë', 'dhe', 'qi', 'mirepo', 'tona', 'që', 'u', 'këtu', 'cilet', 'jene', 'tjere', 'gjë', 'së', 'gjatë', 'duhej', 't', 'dhene', 'thuhet', 'po', 'une', 'dy', 'cfare', 'ndërsa', 'sepse', 'edhe', 'cilen', 'to', 'meqenese', 'meje', 'tij', 'qene', 'jeni', 'them', 'përket', 'keto', 'ni', 'këso', 'asaj', 'ajo', 'sic', 'vetëm', 'ketyre', 'andaj', 'na', 'sa', 'kesaj', 'cili', 'këtyre', 'domethene', 'mirëpo', 'cilën', 'mos', 'madh', 'qenë', 'cilët', 'thënë', 'jemi', 'fjale', 'soje', 'neve', 'gjitha', 'kështu', 'vet', 'kur', 'ty', 'meqë', 'meqenëse', 'jush', 'ketë', 'para', 'kush', 'i', 'mua', 'dite', 'ate', 'për', 'tepër', 'nesh', 'meqe', 'ketu', 'ku', 'disa', 'ato', 'mbi', 'gje', 'ne', 'është', 'tille', 'teje', 'megjithate', 'ju', 'nese', 'saj', 'ashtu', 'më', 'mbasi', 'te', 'thene', 'jo', 'ditë', 'nuk', 'gjithe', 'shume', 'nje', 'tanë', 'mund', 'aqsa', 'sot', 'këto', 'tjera', 'tjetër', 'tjeter', 'atë', 'kisha', 'megjithatë', 'këtij', 'nëse', 'dimë', 'eshte', 'vazhdojmë', 'ka', 'kam', 'kesi', 'je', 'vazhdojme', 'duke', 'dime', 'kinse', 'por', 'kane', 'pika', 'keni', 'beje', 'ky', 'parasysh', 'apo', 'gjithë', 'me', 'ata', 'çfarë', 'jam', 'juve', 'kete', 'a', 'pra', 'qe', 'tash', 'në', 'vetë', 'vec', 'as', 'ndonese', 'tani', 'pak', 'e', 'shumë', 'إذ', 'إذا', 'إذما', 'إذن', 'أف', 'أقل', 'أكثر', 'ألا', 'إلا', 'التي', 'الذي', 'الذين', 'اللاتي', 'اللائي', 'اللتان', 'اللتيا', 'اللتين', 'اللذان', 'اللذين', 'اللواتي', 'إلى', 'إليك', 'إليكم', 'إليكما', 'إليكن', 'أم', 'أما', 'أما', 'إما', 'أن', 'إن', 'إنا', 'أنا', 'أنت', 'أنتم', 'أنتما', 'أنتن', 'إنما', 'إنه', 'أنى', 'أنى', 'آه', 'آها', 'أو', 'أولاء', 'أولئك', 'أوه', 'آي', 'أي', 'أيها', 'إي', 'أين', 'أين', 'أينما', 'إيه', 'بخ', 'بس', 'بعد', 'بعض', 'بك', 'بكم', 'بكم', 'بكما', 'بكن', 'بل', 'بلى', 'بما', 'بماذا', 'بمن', 'بنا', 'به', 'بها', 'بهم', 'بهما', 'بهن', 'بي', 'بين', 'بيد', 'تلك', 'تلكم', 'تلكما', 'ته', 'تي', 'تين', 'تينك', 'ثم', 'ثمة', 'حاشا', 'حبذا', 'حتى', 'حيث', 'حيثما', 'حين', 'خلا', 'دون', 'ذا', 'ذات', 'ذاك', 'ذان', 'ذانك', 'ذلك', 'ذلكم', 'ذلكما', 'ذلكن', 'ذه', 'ذو', 'ذوا', 'ذواتا', 'ذواتي', 'ذي', 'ذين', 'ذينك', 'ريث', 'سوف', 'سوى', 'شتان', 'عدا', 'عسى', 'عل', 'على', 'عليك', 'عليه', 'عما', 'عن', 'عند', 'غير', 'فإذا', 'فإن', 'فلا', 'فمن', 'في', 'فيم', 'فيما', 'فيه', 'فيها', 'قد', 'كأن', 'كأنما', 'كأي', 'كأين', 'كذا', 'كذلك', 'كل', 'كلا', 'كلاهما', 'كلتا', 'كلما', 'كليكما', 'كليهما', 'كم', 'كم', 'كما', 'كي', 'كيت', 'كيف', 'كيفما', 'لا', 'لاسيما', 'لدى', 'لست', 'لستم', 'لستما', 'لستن', 'لسن', 'لسنا', 'لعل', 'لك', 'لكم', 'لكما', 'لكن', 'لكنما', 'لكي', 'لكيلا', 'لم', 'لما', 'لن', 'لنا', 'له', 'لها', 'لهم', 'لهما', 'لهن', 'لو', 'لولا', 'لوما', 'لي', 'لئن', 'ليت', 'ليس', 'ليسا', 'ليست', 'ليستا', 'ليسوا', 'ما', 'ماذا', 'متى', 'مذ', 'مع', 'مما', 'ممن', 'من', 'منه', 'منها', 'منذ', 'مه', 'مهما', 'نحن', 'نحو', 'نعم', 'ها', 'هاتان', 'هاته', 'هاتي', 'هاتين', 'هاك', 'هاهنا', 'هذا', 'هذان', 'هذه', 'هذي', 'هذين', 'هكذا', 'هل', 'هلا', 'هم', 'هما', 'هن', 'هنا', 'هناك', 'هنالك', 'هو', 'هؤلاء', 'هي', 'هيا', 'هيت', 'هيهات', 'والذي', 'والذين', 'وإذ', 'وإذا', 'وإن', 'ولا', 'ولكن', 'ولو', 'وما', 'ومن', 'وهو', 'يا', 'أبٌ', 'أخٌ', 'حمٌ', 'فو', 'أنتِ', 'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر', 'جانفي', 'فيفري', 'مارس', 'أفريل', 'ماي', 'جوان', 'جويلية', 'أوت', 'كانون', 'شباط', 'آذار', 'نيسان', 'أيار', 'حزيران', 'تموز', 'آب', 'أيلول', 'تشرين', 'دولار', 'دينار', 'ريال', 'درهم', 'ليرة', 'جنيه', 'قرش', 'مليم', 'فلس', 'هللة', 'سنتيم', 'يورو', 'ين', 'يوان', 'شيكل', 'واحد', 'اثنان', 'ثلاثة', 'أربعة', 'خمسة', 'ستة', 'سبعة', 'ثمانية', 'تسعة', 'عشرة', 'أحد', 'اثنا', 'اثني', 'إحدى', 'ثلاث', 'أربع', 'خمس', 'ست', 'سبع', 'ثماني', 'تسع', 'عشر', 'ثمان', 'سبت', 'أحد', 'اثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'أول', 'ثان', 'ثاني', 'ثالث', 'رابع', 'خامس', 'سادس', 'سابع', 'ثامن', 'تاسع', 'عاشر', 'حادي', 'أ', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', 'ء', 'ى', 'آ', 'ؤ', 'ئ', 'أ', 'ة', 'ألف', 'باء', 'تاء', 'ثاء', 'جيم', 'حاء', 'خاء', 'دال', 'ذال', 'راء', 'زاي', 'سين', 'شين', 'صاد', 'ضاد', 'طاء', 'ظاء', 'عين', 'غين', 'فاء', 'قاف', 'كاف', 'لام', 'ميم', 'نون', 'هاء', 'واو', 'ياء', 'همزة', 'ي', 'نا', 'ك', 'كن', 'ه', 'إياه', 'إياها', 'إياهما', 'إياهم', 'إياهن', 'إياك', 'إياكما', 'إياكم', 'إياك', 'إياكن', 'إياي', 'إيانا', 'أولالك', 'تانِ', 'تانِك', 'تِه', 'تِي', 'تَيْنِ', 'ثمّ', 'ثمّة', 'ذانِ', 'ذِه', 'ذِي', 'ذَيْنِ', 'هَؤلاء', 'هَاتانِ', 'هَاتِه', 'هَاتِي', 'هَاتَيْنِ', 'هَذا', 'هَذانِ', 'هَذِه', 'هَذِي', 'هَذَيْنِ', 'الألى', 'الألاء', 'أل', 'أنّى', 'أيّ', 'ّأيّان', 'أنّى', 'أيّ', 'ّأيّان', 'ذيت', 'كأيّ', 'كأيّن', 'بضع', 'فلان', 'وا', 'آمينَ', 'آهِ', 'آهٍ', 'آهاً', 'أُفٍّ', 'أُفٍّ', 'أفٍّ', 'أمامك', 'أمامكَ', 'أوّهْ', 'إلَيْكَ', 'إلَيْكَ', 'إليكَ', 'إليكنّ', 'إيهٍ', 'بخٍ', 'بسّ', 'بَسْ', 'بطآن', 'بَلْهَ', 'حاي', 'حَذارِ', 'حيَّ', 'حيَّ', 'دونك', 'رويدك', 'سرعان', 'شتانَ', 'شَتَّانَ', 'صهْ', 'صهٍ', 'طاق', 'طَق', 'عَدَسْ', 'كِخ', 'مكانَك', 'مكانَك', 'مكانَك', 'مكانكم', 'مكانكما', 'مكانكنّ', 'نَخْ', 'هاكَ', 'هَجْ', 'هلم', 'هيّا', 'هَيْهات', 'وا', 'واهاً', 'وراءَك', 'وُشْكَانَ', 'وَيْ', 'يفعلان', 'تفعلان', 'يفعلون', 'تفعلون', 'تفعلين', 'اتخذ', 'ألفى', 'تخذ', 'ترك', 'تعلَّم', 'جعل', 'حجا', 'حبيب', 'خال', 'حسب', 'خال', 'درى', 'رأى', 'زعم', 'صبر', 'ظنَّ', 'عدَّ', 'علم', 'غادر', 'ذهب', 'وجد', 'ورد', 'وهب', 'أسكن', 'أطعم', 'أعطى', 'رزق', 'زود', 'سقى', 'كسا', 'أخبر', 'أرى', 'أعلم', 'أنبأ', 'حدَث', 'خبَّر', 'نبَّا', 'أفعل به', 'ما أفعله', 'بئس', 'ساء', 'طالما', 'قلما', 'لات', 'لكنَّ', 'ءَ', 'أجل', 'إذاً', 'أمّا', 'إمّا', 'إنَّ', 'أنًّ', 'أى', 'إى', 'أيا', 'ب', 'ثمَّ', 'جلل', 'جير', 'رُبَّ', 'س', 'علًّ', 'ف', 'كأنّ', 'كلَّا', 'كى', 'ل', 'لات', 'لعلَّ', 'لكنَّ', 'لكنَّ', 'م', 'نَّ', 'هلّا', 'وا', 'أل', 'إلّا', 'ت', 'ك', 'لمّا', 'ن', 'ه', 'و', 'ا', 'ي', 'تجاه', 'تلقاء', 'جميع', 'حسب', 'سبحان', 'شبه', 'لعمر', 'مثل', 'معاذ', 'أبو', 'أخو', 'حمو', 'فو', 'مئة', 'مئتان', 'ثلاثمئة', 'أربعمئة', 'خمسمئة', 'ستمئة', 'سبعمئة', 'ثمنمئة', 'تسعمئة', 'مائة', 'ثلاثمائة', 'أربعمائة', 'خمسمائة', 'ستمائة', 'سبعمائة', 'ثمانمئة', 'تسعمائة', 'عشرون', 'ثلاثون', 'اربعون', 'خمسون', 'ستون', 'سبعون', 'ثمانون', 'تسعون', 'عشرين', 'ثلاثين', 'اربعين', 'خمسين', 'ستين', 'سبعين', 'ثمانين', 'تسعين', 'بضع', 'نيف', 'أجمع', 'جميع', 'عامة', 'عين', 'نفس', 'لا سيما', 'أصلا', 'أهلا', 'أيضا', 'بؤسا', 'بعدا', 'بغتة', 'تعسا', 'حقا', 'حمدا', 'خلافا', 'خاصة', 'دواليك', 'سحقا', 'سرا', 'سمعا', 'صبرا', 'صدقا', 'صراحة', 'طرا', 'عجبا', 'عيانا', 'غالبا', 'فرادى', 'فضلا', 'قاطبة', 'كثيرا', 'لبيك', 'معاذ', 'أبدا', 'إزاء', 'أصلا', 'الآن', 'أمد', 'أمس', 'آنفا', 'آناء', 'أنّى', 'أول', 'أيّان', 'تارة', 'ثمّ', 'ثمّة', 'حقا', 'صباح', 'مساء', 'ضحوة', 'عوض', 'غدا', 'غداة', 'قطّ', 'كلّما', 'لدن', 'لمّا', 'مرّة', 'قبل', 'خلف', 'أمام', 'فوق', 'تحت', 'يمين', 'شمال', 'ارتدّ', 'استحال', 'أصبح', 'أضحى', 'آض', 'أمسى', 'انقلب', 'بات', 'تبدّل', 'تحوّل', 'حار', 'رجع', 'راح', 'صار', 'ظلّ', 'عاد', 'غدا', 'كان', 'ما انفك', 'ما برح', 'مادام', 'مازال', 'مافتئ', 'ابتدأ', 'أخذ', 'اخلولق', 'أقبل', 'انبرى', 'أنشأ', 'أوشك', 'جعل', 'حرى', 'شرع', 'طفق', 'علق', 'قام', 'كرب', 'كاد', 'هبّa', 'ad', 'altı', 'altmış', 'amma', 'arasında', 'artıq', 'ay', 'az', 'bax', 'belə', 'bəli', 'bəlkə', 'beş', 'bəy', 'bəzən', 'bəzi', 'bilər', 'bir', 'biraz', 'biri', 'birşey', 'biz', 'bizim', 'bizlər', 'bu', 'buna', 'bundan', 'bunların', 'bunu', 'bunun', 'buradan', 'bütün', 'ci', 'cı', 'çox', 'cu', 'cü', 'çünki', 'da', 'daha', 'də', 'dedi', 'dək', 'dən', 'dəqiqə', 'deyil', 'dir', 'doqquz', 'doqsan', 'dörd', 'düz', 'ə', 'edən', 'edir', 'əgər', 'əlbəttə', 'elə', 'əlli', 'ən', 'əslində', 'et', 'etdi', 'etmə', 'etmək', 'faiz', 'gilə', 'görə', 'ha', 'haqqında', 'harada', 'hə', 'heç', 'həm', 'həmin', 'həmişə', 'hər', 'ı', 'idi', 'iki', 'il', 'ildə', 'ilə', 'ilk', 'in', 'indi', 'isə', 'istifadə', 'iyirmi', 'ki', 'kim', 'kimə', 'kimi', 'lakin', 'lap', 'məhz', 'mən', 'mənə', 'mirşey', 'nə', 'nəhayət', 'niyə', 'o', 'obirisi', 'of', 'olan', 'olar', 'olaraq', 'oldu', 'olduğu', 'olmadı', 'olmaz', 'olmuşdur', 'olsun', 'olur', 'on', 'ona', 'ondan', 'onlar', 'onlardan', 'onların ', 'onsuzda', 'onu', 'onun', 'oradan', 'otuz', 'öz', 'özü', 'qarşı', 'qədər', 'qırx', 'saat', 'sadəcə', 'saniyə', 'səhv', 'səkkiz', 'səksən', 'sən', 'sənə', 'sənin', 'siz', 'sizin', 'sizlər', 'sonra', 'təəssüf', 'ü', 'üç', 'üçün', 'var', 'və', 'xan', 'xanım', 'xeyr', 'ya', 'yalnız', 'yaxşı', 'yeddi', 'yenə', 'yəni', 'yetmiş', 'yox', 'yoxdur', 'yoxsa', 'yüz', 'zamanahala', 'aitzitik', 'al', 'ala ', 'alabadere', 'alabaina', 'alabaina', 'aldiz ', 'alta', 'amaitu', 'amaitzeko', 'anitz', 'antzina', 'arabera', 'arabera', 'arabera', 'argi', 'arratsaldero', 'arte', 'artean', 'asko', 'aspaldiko', 'aurrera', 'aurrera', 'azkenez', 'azkenik', 'azkenik', 'ba', 'bada', 'bada ', 'bada ', 'bada ', 'badarik', 'badarik', 'badarik ', 'badere', 'bai', 'baina', 'baina', 'baina ', 'baino', 'baino', 'baino', 'baino', 'baita', 'baizik ', 'baldin', 'baldin', 'barren', 'bat', 'batean', 'batean', 'batean', 'batean', 'batek', 'baten', 'batera', 'batez', 'bati', 'batzuei', 'batzuek', 'batzuetan', 'batzuk', 'bazen', 'bederen', 'bederik', 'beharrez', 'behiala', 'behin', 'behin', 'behin', 'behin', 'behinik', 'behinola', 'behintzat', 'bera', 'beraiek', 'beranduago', 'berau', 'berauek', 'beraz', 'beraz ', 'bere', 'berean', 'berebat', 'berehala', 'berori', 'beroriek', 'berriro', 'berriz', 'bertzalde', 'bertzenaz', 'bestalde', 'beste', 'bestela', 'besterik', 'bezain', 'bezala', 'bide', 'bien', 'bigarrenez', 'bigarrenik', 'bitartean', 'bitartean', 'bizkitartean', 'bukaeran', 'bukatzeko ', 'da', 'dago', 'dago', 'dela', 'dela', 'dela', 'delarik', 'den', 'dena', 'dena', 'dezadan', 'dira', 'ditu', 'du', 'dute', 'edo', 'edo ', 'edota ', 'egin', 'egin', 'egun', 'egun', 'egunean', 'emateko', 'era', 'erdi', 'ere', 'ere', 'ere', 'ere', 'ere ', 'esan', 'esan', 'esanak', 'esandakoaren', 'eta', 'eta', 'eta', 'eta', 'eta ', 'eta ', 'eurak', 'ez', 'ez ', 'ez ', 'eze ', 'ezen', 'ezer', 'ezezik', 'ezik', 'ezpabere ', 'ezpada ', 'ezpere', 'ezperen ', 'ezta', 'funtsean', 'gabe', 'gain', 'gainera ', 'gainera \t', 'gainerontzean ', 'gaur', 'gero', 'gero', 'gero', 'geroago', 'gisa', 'gu', 'gutxi', 'guzti', 'guztia', 'guztiz ', 'haatik', 'haiei', 'haiek', 'haietan', 'hain', 'hainbeste', 'hainbestez ', 'hala', 'hala', 'hala', 'halaber', 'halako', 'halatan', 'han', 'handik', 'hango', 'hara', 'hargatik', 'hari', 'hark', 'hartan', 'hartan', 'hasi', 'hasi', 'hasiera', 'hasieran', 'hasteaz', 'hasteko', 'hasteko', 'hau', 'hau', 'hau', 'hau', 'hau', 'hau', 'hauei', 'hauek', 'hauetan', 'hemen', 'hemendik', 'hemengo', 'hi', 'hona', 'honebestez', 'honek', 'honela', 'honela', 'honela', 'honen', 'honen', 'honetan', 'honetaz', 'honi', 'hor', 'hori', 'hori', 'hori', 'horiei', 'horiek', 'horietan', 'horko', 'horra \t', 'horratik', 'horregatik', 'horregatik', 'horrek', 'horrela', 'horrela', 'horrela', 'horren', 'horrenbestez', 'horretan', 'horri', 'hortaz', 'hortaz', 'hortik', 'hura', 'ikusi', 'ikusi', 'izan', 'izan', 'izan', 'jarraituz', 'kariaz', 'kasuaz', 'kontuan', 'laburbilduz', 'laburki', 'laster', 'laster', 'lehen', 'lehen', 'lehen', 'lehen', 'lehenengo', 'lehenengo', 'lehenik', 'lehen-lehenik', 'litzateke', 'medio', 'mendean', 'mundura', 'nahiz', 'ni', 'noiz', 'nola', 'non', 'nondik', 'nongo', 'nor', 'nora', 'on', 'ondoren', 'ondorio', 'ondorioz', 'ondorioz', 'orain', 'ordea ', 'orduan', 'orduan', 'orduan ', 'orduko', 'ordura', 'orobat', 'ostean', 'ostera', 'osterantzean ', 'pentsatuz', 'ustez', 'ze', 'zein', 'zein ', 'zen', 'zen', 'zenbait', 'zenbat', 'zer', 'zeren', 'zergatik', 'zergatik', 'ziren', 'zituen', 'zu', 'zuek', 'zuen', 'zuten', 'zuzen', 'на', 'не', 'што', 'па', 'да', 'за', 'як', 'для', 'гэта', 'ад', 'яго', 'аб', 'ён', 'калi', 'якiя', 'мы', 'больш', 'таксама', 'iх', 'толькi', 'пра', 'каб', 'гэтым', 'так', 'але', 'яшчэ', 'тым', 'якi', 'яе', 'пры', 'цi', 'яны', 'цяпер', 'таму', 'пасля', 'каля', 'гэтага', 'годзе', 'тыс', 'таго', 'тут', 'тысяч', 'ўжо', 'дзе', 'якая', 'са', 'яна', 'гэты', 'пад', 'можна', 'паводле', 'вельмi', 'ва', 'то', 'сёння', 'можа', 'ўсё', 'нас', 'вось', 'нават', 'або', 'сёлета', 'іх', 'той', 'ужо', 'чым', 'тое', 'хто', 'жа', 'без', 'праз', 'мяне', 'аднак', 'бо', 'мне', 'там', 'адзiн', 'два', 'сярод', 'гэтай', 'сябе', 'калі', 'толькі', 'дарэчы', 'млн', 'падчас', 'вы', 'усё', 'нашай', 'якія', 'iм', 'разам', 'акрамя', 'ды', 'якiх', 'мае', 'стала', 'раней', 'шмат', 'амаль', 'усе', 'першы', 'пакуль', 'напрыклад', 'тысячы', 'ўсе', 'ты', 'якой', 'раз', 'свае', 'iншых', 'гэтыя', 'тры', 'яму', 'які', 'сваю', 'памiж', 'ўсiх', 'ёй', 'сваёй', 'хоць', 'некалькi', 'аднаго', 'менавiта', 'проста', 'потым', 'нi', 'заўсёды', 'менш', 'тады', 'нам', 'свой', 'якiм', 'свята', 'такiм', 'перад', 'вядома', 'бы', 'якое', 'мая', 'тых', 'гэтых', 'такiя', 'зараз', 'адной', 'адна', 'адным', 'якога', 'добра', 'над', 'летась', 'справа', 'кожны', 'свайго', 'сваiх', 'неабходна', 'такiх', 'зноў', 'мiльёнаў', 'прычым', 'iншыя', 'днём', 'млрд', 'сам', 'ці', 'нашы', 'сабе', 'адразу', 'усяго', 'двух', 'тыя', 'нашых', 'якую', 'чаго', 'асаблiва', 'сваiм', 'першым', 'згодна', 'такое', 'найбольш', 'такi', 'дзве', 'ім', 'вельмі', 'наша', 'дзвюх', 'ну', 'сваё', 'праўда', 'вас', 'трох', 'зусiм', 'пяць', 'некаторыя', 'дык', 'крыху', 'чаму', 'такой', 'магчыма', 'сапраўды', 'такая', 'вам', 'нешта', 'усiх', 'адно', 'далей', 'значыць', 'чатыры', 'самых', 'хутка', 'самы', 'дзякуючы', 'наш', 'часта', 'самым', 'першай', 'адзін', 'супраць', 'яно', 'другi', 'удзень', 'нiчога', 'мой', 'побач', 'অতএব', 'অথচ', 'অথবা', 'অনুযায়ী', 'অনেক', 'অনেকে', 'অনেকেই', 'অন্তত', 'অন্য', 'অবধি', 'অবশ্য', 'অর্থাত', 'আই', 'আগামী', 'আগে', 'আগেই', 'আছে', 'আজ', 'আদ্যভাগে', 'আপনার', 'আপনি', 'আবার', 'আমরা', 'আমাকে', 'আমাদের', 'আমার', 'আমি', 'আর', 'আরও', 'ই', 'ইত্যাদি', 'ইহা', 'উচিত', 'উত্তর', 'উনি', 'উপর', 'উপরে', 'এ', 'এঁদের', 'এঁরা', 'এই', 'একই', 'একটি', 'একবার', 'একে', 'এক্', 'এখন', 'এখনও', 'এখানে', 'এখানেই', 'এটা', 'এটাই', 'এটি', 'এত', 'এতটাই', 'এতে', 'এদের', 'এব', 'এবং', 'এবার', 'এমন', 'এমনকী', 'এমনি', 'এর', 'এরা', 'এল', 'এস', 'এসে', 'ঐ', 'ও', 'ওঁদের', 'ওঁর', 'ওঁরা', 'ওই', 'ওকে', 'ওখানে', 'ওদের', 'ওর', 'ওরা', 'কখনও', 'কত', 'কবে', 'কমনে', 'কয়েক', 'কয়েকটি', 'করছে', 'করছেন', 'করতে', 'করবে', 'করবেন', 'করলে', 'করলেন', 'করা', 'করাই', 'করায়', 'করার', 'করি', 'করিতে', 'করিয়া', 'করিয়ে', 'করে', 'করেই', 'করেছিলেন', 'করেছে', 'করেছেন', 'করেন', 'কাউকে', 'কাছ', 'কাছে', 'কাজ', 'কাজে', 'কারও', 'কারণ', 'কি', 'কিংবা', 'কিছু', 'কিছুই', 'কিন্তু', 'কী', 'কে', 'কেউ', 'কেউই', 'কেখা', 'কেন', 'কোটি', 'কোন', 'কোনও', 'কোনো', 'ক্ষেত্রে', 'কয়েক', 'খুব', 'গিয়ে', 'গিয়েছে', 'গিয়ে', 'গুলি', 'গেছে', 'গেল', 'গেলে', 'গোটা', 'চলে', 'চান', 'চায়', 'চার', 'চালু', 'চেয়ে', 'চেষ্টা', 'ছাড়া', 'ছাড়াও', 'ছিল', 'ছিলেন', 'জন', 'জনকে', 'জনের', 'জন্য', 'জন্যওজে', 'জানতে', 'জানা', 'জানানো', 'জানায়', 'জানিয়ে', 'জানিয়েছে', 'জে', 'জ্নজন', 'টি', 'ঠিক', 'তখন', 'তত', 'তথা', 'তবু', 'তবে', 'তা', 'তাঁকে', 'তাঁদের', 'তাঁর', 'তাঁরা', 'তাঁাহারা', 'তাই', 'তাও', 'তাকে', 'তাতে', 'তাদের', 'তার', 'তারপর', 'তারা', 'তারৈ', 'তাহলে', 'তাহা', 'তাহাতে', 'তাহার', 'তিনঐ', 'তিনি', 'তিনিও', 'তুমি', 'তুলে', 'তেমন', 'তো', 'তোমার', 'থাকবে', 'থাকবেন', 'থাকা', 'থাকায়', 'থাকে', 'থাকেন', 'থেকে', 'থেকেই', 'থেকেও', 'দিকে', 'দিতে', 'দিন', 'দিয়ে', 'দিয়েছে', 'দিয়েছেন', 'দিলেন', 'দু', 'দুই', 'দুটি', 'দুটো', 'দেওয়া', 'দেওয়ার', 'দেওয়া', 'দেখতে', 'দেখা', 'দেখে', 'দেন', 'দেয়', 'দ্বারা', 'ধরা', 'ধরে', 'ধামার', 'নতুন', 'নয়', 'না', 'নাই', 'নাকি', 'নাগাদ', 'নানা', 'নিজে', 'নিজেই', 'নিজেদের', 'নিজের', 'নিতে', 'নিয়ে', 'নিয়ে', 'নেই', 'নেওয়া', 'নেওয়ার', 'নেওয়া', 'নয়', 'পক্ষে', 'পর', 'পরে', 'পরেই', 'পরেও', 'পর্যন্ত', 'পাওয়া', 'পাচ', 'পারি', 'পারে', 'পারেন', 'পি', 'পেয়ে', 'পেয়্র্', 'প্রতি', 'প্রথম', 'প্রভৃতি', 'প্রযন্ত', 'প্রাথমিক', 'প্রায়', 'প্রায়', 'ফলে', 'ফিরে', 'ফের', 'বক্তব্য', 'বদলে', 'বন', 'বরং', 'বলতে', 'বলল', 'বললেন', 'বলা', 'বলে', 'বলেছেন', 'বলেন', 'বসে', 'বহু', 'বা', 'বাদে', 'বার', 'বি', 'বিনা', 'বিভিন্ন', 'বিশেষ', 'বিষয়টি', 'বেশ', 'বেশি', 'ব্যবহার', 'ব্যাপারে', 'ভাবে', 'ভাবেই', 'মতো', 'মতোই', 'মধ্যভাগে', 'মধ্যে', 'মধ্যেই', 'মধ্যেও', 'মনে', 'মাত্র', 'মাধ্যমে', 'মোট', 'মোটেই', 'যখন', 'যত', 'যতটা', 'যথেষ্ট', 'যদি', 'যদিও', 'যা', 'যাঁর', 'যাঁরা', 'যাওয়া', 'যাওয়ার', 'যাওয়া', 'যাকে', 'যাচ্ছে', 'যাতে', 'যাদের', 'যান', 'যাবে', 'যায়', 'যার', 'যারা', 'যিনি', 'যে', 'যেখানে', 'যেতে', 'যেন', 'যেমন', 'র', 'রকম', 'রয়েছে', 'রাখা', 'রেখে', 'লক্ষ', 'শুধু', 'শুরু', 'সঙ্গে', 'সঙ্গেও', 'সব', 'সবার', 'সমস্ত', 'সম্প্রতি', 'সহ', 'সহিত', 'সাধারণ', 'সামনে', 'সি', 'সুতরাং', 'সে', 'সেই', 'সেখান', 'সেখানে', 'সেটা', 'সেটাই', 'সেটাও', 'সেটি', 'স্পষ্ট', 'স্বয়ং', 'হইতে', 'হইবে', 'হইয়া', 'হওয়া', 'হওয়ায়', 'হওয়ার', 'হচ্ছে', 'হত', 'হতে', 'হতেই', 'হন', 'হবে', 'হবেন', 'হয়', 'হয়তো', 'হয়নি', 'হয়ে', 'হয়েই', 'হয়েছিল', 'হয়েছে', 'হয়েছেন', 'হল', 'হলে', 'হলেই', 'হলেও', 'হলো', 'হাজার', 'হিসাবে', 'হৈলে', 'হোক', 'হয়a', 'abans', 'ací', 'ah', 'així', 'això', 'al', 'aleshores', 'algun', 'alguna', 'algunes', 'alguns', 'alhora', 'allà', 'allí', 'allò', 'als', 'altra', 'altre', 'altres', 'amb', 'ambdues', 'ambdós', 'anar', 'ans', 'apa', 'aquell', 'aquella', 'aquelles', 'aquells', 'aquest', 'aquesta', 'aquestes', 'aquests', 'aquí', 'baix', 'bastant', 'bé', 'cada', 'cadascuna', 'cadascunes', 'cadascuns', 'cadascú', 'com', 'consegueixo', 'conseguim', 'conseguir', 'consigueix', 'consigueixen', 'consigueixes', 'contra', "d'un", "d'una", "d'unes", "d'uns", 'dalt', 'de', 'del', 'dels', 'des', 'des de', 'després', 'dins', 'dintre', 'donat', 'doncs', 'durant', 'e', 'eh', 'el', 'elles', 'ells', 'els', 'em', 'en', 'encara', 'ens', 'entre', 'era', 'erem', 'eren', 'eres', 'es', 'esta', 'estan', 'estat', 'estava', 'estaven', 'estem', 'esteu', 'estic', 'està', 'estàvem', 'estàveu', 'et', 'etc', 'ets', 'fa', 'faig', 'fan', 'fas', 'fem', 'fer', 'feu', 'fi', 'fins', 'fora', 'gairebé', 'ha', 'han', 'has', 'haver', 'havia', 'he', 'hem', 'heu', 'hi', 'ho', 'i', 'igual', 'iguals', 'inclòs', 'ja', 'jo', "l'hi", 'la', 'les', 'li', "li'n", 'llarg', 'llavors', "m'he", 'ma', 'mal', 'malgrat', 'mateix', 'mateixa', 'mateixes', 'mateixos', 'me', 'mentre', 'meu', 'meus', 'meva', 'meves', 'mode', 'molt', 'molta', 'moltes', 'molts', 'mon', 'mons', 'més', "n'he", "n'hi", 'ne', 'ni', 'no', 'nogensmenys', 'només', 'nosaltres', 'nostra', 'nostre', 'nostres', 'o', 'oh', 'oi', 'on', 'pas', 'pel', 'pels', 'per', 'per que', 'perquè', 'però', 'poc', 'poca', 'pocs', 'podem', 'poden', 'poder', 'podeu', 'poques', 'potser', 'primer', 'propi', 'puc', 'qual', 'quals', 'quan', 'quant', 'que', 'quelcom', 'qui', 'quin', 'quina', 'quines', 'quins', 'què', "s'ha", "s'han", 'sa', 'sabem', 'saben', 'saber', 'sabeu', 'sap', 'saps', 'semblant', 'semblants', 'sense', 'ser', 'ses', 'seu', 'seus', 'seva', 'seves', 'si', 'sobre', 'sobretot', 'soc', 'solament', 'sols', 'som', 'son', 'sons', 'sota', 'sou', 'sóc', 'són', "t'ha", "t'han", "t'he", 'ta', 'tal', 'també', 'tampoc', 'tan', 'tant', 'tanta', 'tantes', 'te', 'tene', 'tenim', 'tenir', 'teniu', 'teu', 'teus', 'teva', 'teves', 'tinc', 'ton', 'tons', 'tot', 'tota', 'totes', 'tots', 'un', 'una', 'unes', 'uns', 'us', 'va', 'vaig', 'vam', 'van', 'vas', 'veu', 'vosaltres', 'vostra', 'vostre', 'vostres', 'érem', 'éreu', 'és', 'éssent', 'últim', 'ús一', '一下', '一些', '一切', '一则', '一天', '一定', '一方面', '一旦', '一时', '一来', '一样', '一次', '一片', '一直', '一致', '一般', '一起', '一边', '一面', '万一', '上下', '上升', '上去', '上来', '上述', '上面', '下列', '下去', '下来', '下面', '不一', '不久', '不仅', '不会', '不但', '不光', '不单', '不变', '不只', '不可', '不同', '不够', '不如'

In [85]:
print(stopwords.words("english"))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [87]:
print(stopwords.words("tamil"))

['அங்கு', 'அங்கே', 'அடுத்த', 'அதனால்', 'அதன்', 'அதற்கு', 'அதிக', 'அதில்', 'அது', 'அதே', 'அதை', 'அந்த', 'அந்தக்', 'அந்தப்', 'அன்று', 'அல்லது', 'அவன்', 'அவரது', 'அவர்', 'அவர்கள்', 'அவள்', 'அவை', 'ஆகிய', 'ஆகியோர்', 'ஆகும்', 'இங்கு', 'இங்கே', 'இடத்தில்', 'இடம்', 'இதனால்', 'இதனை', 'இதன்', 'இதற்கு', 'இதில்', 'இது', 'இதை', 'இந்த', 'இந்தக்', 'இந்தத்', 'இந்தப்', 'இன்னும்', 'இப்போது', 'இரு', 'இருக்கும்', 'இருந்த', 'இருந்தது', 'இருந்து', 'இவர்', 'இவை', 'உன்', 'உள்ள', 'உள்ளது', 'உள்ளன', 'எந்த', 'என', 'எனக்', 'எனக்கு', 'எனப்படும்', 'எனவும்', 'எனவே', 'எனினும்', 'எனும்', 'என்', 'என்ன', 'என்னும்', 'என்பது', 'என்பதை', 'என்ற', 'என்று', 'என்றும்', 'எல்லாம்', 'ஏன்', 'ஒரு', 'ஒரே', 'ஓர்', 'கொண்ட', 'கொண்டு', 'கொள்ள', 'சற்று', 'சிறு', 'சில', 'சேர்ந்த', 'தனது', 'தன்', 'தவிர', 'தான்', 'நான்', 'நாம்', 'நீ', 'பற்றி', 'பற்றிய', 'பல', 'பலரும்', 'பல்வேறு', 'பின்', 'பின்னர்', 'பிற', 'பிறகு', 'பெரும்', 'பேர்', 'போது', 'போன்ற', 'போல', 'போல்', 'மட்டுமே', 'மட்டும்', 'மற்ற', 'மற்றும்', 'மிக', 'மிகவும்', 'மீது', 'முதல்', 'முறை', 'மேலும்', 'மேல்', 'யார்', 'வந்த', 'வந்து', 'வரும்', 'வரை', 'வரையில்', 'விட', 'விட்டு', 'வேண்டும்', 'வேறு']

In [93]:
# print(stopwords.words("hinglish"))

In [97]:
len(stopwords.words("english"))

198

In [99]:
stp_wrds = stopwords.words("english")

In [103]:
"Is".lower() in stp_wrds

True

In [105]:
sent_tok

['Machine learning is a subset of Artificial Intelligence (AI) that enables computers to learn from data and make predictions without being explicitly programmed.',
 "If you're new to this field, this tutorial will provide a comprehensive understanding of machine learning,its types, algorithms, tools, and practical applications."]

In [111]:
word_tokens = word_tokenize(sent_tok[0])

In [117]:
[lm.lemmatize(word,pos='v') for word in word_tokens]

['Machine',
 'learn',
 'be',
 'a',
 'subset',
 'of',
 'Artificial',
 'Intelligence',
 '(',
 'AI',
 ')',
 'that',
 'enable',
 'computers',
 'to',
 'learn',
 'from',
 'data',
 'and',
 'make',
 'predictions',
 'without',
 'be',
 'explicitly',
 'program',
 '.']

In [119]:
[lm.lemmatize(word,pos='v') for word in word_tokens if word.lower() not in stp_wrds]

['Machine',
 'learn',
 'subset',
 'Artificial',
 'Intelligence',
 '(',
 'AI',
 ')',
 'enable',
 'computers',
 'learn',
 'data',
 'make',
 'predictions',
 'without',
 'explicitly',
 'program',
 '.']

In [121]:
" ".join([lm.lemmatize(word,pos='v') for word in word_tokens if word.lower() not in stp_wrds])

'Machine learn subset Artificial Intelligence ( AI ) enable computers learn data make predictions without explicitly program .'

In [123]:
processed_sent = []
for sentense in sent_tok:
    word_tokens = word_tokenize(sentense)
    lemmatized_words = [lm.lemmatize(word,pos='v') for word in word_tokens if word.lower() not in stp_wrds]
    processed_sent.append(" ".join(lemmatized_words))

In [125]:
processed_sent

['Machine learn subset Artificial Intelligence ( AI ) enable computers learn data make predictions without explicitly program .',
 "'re new field , tutorial provide comprehensive understand machine learn , type , algorithms , tool , practical applications ."]

## Punctuations

In [128]:
import string

In [132]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [134]:
Sent_1 = "Hello, World! Python is amazing."

In [136]:
translator = str.maketrans('','',string.punctuation)

In [152]:
translator1 = str.maketrans('o','a',string.punctuation)

In [156]:
translator2 = str.maketrans('ola','xyz',string.punctuation)

In [ ]:
# str.maketrans(a1,a2,a3)
# a1 : character to be replaced
# a2 : character to be replaced with
# a3 : characters to be deleted or replaced with None

In [150]:
str.maketrans??

Docstring:
Return a translation table usable for str.translate().

If there is only one argument, it must be a dictionary mapping Unicode
ordinals (integers) or characters to Unicode ordinals, strings or None.
Character keys will be then converted to ordinals.
If there are two arguments, they must be strings of equal length, and
in the resulting dictionary, each character in x will be mapped to the
character at the same position in y. If there is a third argument, it
must be a string, whose characters will be mapped to None in the result.
Type:      builtin_function_or_method

In [148]:
# translator

In [140]:
## ASCII Values
ord("!")

33

In [142]:
ord("a")

97

In [144]:
ord("A")

65

In [146]:
Sent_1.translate(translator)

'Hello World Python is amazing'

In [154]:
Sent_1.translate(translator1)

'Hella Warld Pythan is amazing'

In [158]:
Sent_1.translate(translator2)

'Heyyx Wxryd Pythxn is zmzzing'

In [168]:
processed_sent = []
for sentense in sent_tok:
    word_tokens = word_tokenize(sentense)
    lemmatized_words = [lm.lemmatize(word,pos='v') for word in word_tokens if word.lower() not in stp_wrds]
    processed_sent.append(" ".join(lemmatized_words).translate(translator).strip())

In [170]:
processed_sent

['Machine learn subset Artificial Intelligence  AI  enable computers learn data make predictions without explicitly program',
 're new field  tutorial provide comprehensive understand machine learn  type  algorithms  tool  practical applications']

In [166]:
processed_sent[0].strip()

'Machine learn subset Artificial Intelligence  AI  enable computers learn data make predictions without explicitly program'

## POS :: part of speech tagging

In [ ]:
## POS :: part of speech tagging 

# Common Parts of Speech Tags:
# 	•	Noun (NN): Person, place, or thing (e.g., cat, happiness)
# 	•	Pronoun (PRP): He, she, it
# 	•	Verb (VB): Actions or states (e.g., run, is)
# 	•	Adjective (JJ): Describes nouns (e.g., beautiful, large)
# 	•	Adverb (RB): Describes verbs or adjectives (e.g., quickly, very)
# 	•	Preposition (IN): Shows relationship (e.g., on, at, in)
# 	•	Conjunction (CC): Connects words or sentences (e.g., and, but)
# 	•	Determiner (DT): Specifies a noun (e.g., the, some)
# 	•	Interjection (UH): Expresses emotion (e.g., wow, oh)
# 	•	Proper Noun (NNP): Names (e.g., John, India)

In [173]:
nltk.pos_tag(["John"])

[('John', 'NNP')]

In [177]:
nltk.pos_tag(["Krishna","Arjun"])

[('Krishna', 'NNP'), ('Arjun', 'NNP')]

In [183]:
nltk.pos_tag_sents([lemmatized_words])

[[("'re", 'VBP'),
  ('new', 'JJ'),
  ('field', 'NN'),
  (',', ','),
  ('tutorial', 'JJ'),
  ('provide', 'VBP'),
  ('comprehensive', 'JJ'),
  ('understand', 'NN'),
  ('machine', 'NN'),
  ('learn', 'NN'),
  (',', ','),
  ('type', 'NN'),
  (',', ','),
  ('algorithms', 'NN'),
  (',', ','),
  ('tool', 'NN'),
  (',', ','),
  ('practical', 'JJ'),
  ('applications', 'NNS'),
  ('.', '.')]]

In [185]:
# lemmatized_words

## Named entity recognition

In [ ]:
# Common NER Categories:
# 	•	Person (PER): Names of people (e.g., Elon Musk, Marie Curie)
# 	•	Organization (ORG): Companies, institutions, or agencies (e.g., Google, United Nations)
# 	•	Location (LOC): Cities, countries, or geographical landmarks (e.g., Paris, Mount Everest)
# 	•	Date (DATE): Specific dates or periods (e.g., January 2023, 21st century)
# 	•	Time (TIME): Time expressions (e.g., 2:00 PM, morning)
# 	•	Money (MONEY): Monetary values (e.g., $500, €10 million)
# 	•	Percent (PERCENT): Percentages (e.g., 20%, 85%)
# 	•	Event (EVENT): Named events (e.g., Olympics, World War II)
# 	•	Product (PRODUCT): Items or brands (e.g., iPhone, Tesla Model S)
# 	•	Miscellaneous (MISC): Entities that don’t fit standard categories

In [188]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [190]:
text = "Sundar Pichai became the CEO of Google in 2015, and he was born in Chennai, India."

In [192]:
doc = nlp(text)

In [194]:
doc

Sundar Pichai became the CEO of Google in 2015, and he was born in Chennai, India.

In [196]:
doc.ents

(Sundar Pichai, Google, 2015, Chennai, India)

In [200]:
doc.ents[0].label_

'PERSON'

In [202]:
for ent in doc.ents:
    print(ent,"-->",ent.label_)

Sundar Pichai --> PERSON
Google --> ORG
2015 --> DATE
Chennai --> GPE
India --> GPE

In [204]:
from spacy import displacy

In [206]:
displacy.serve(doc,auto_select_port=True)

/opt/anaconda3/lib/python3.12/site-packages/spacy/util.py:1835: UserWarning: [W124] 0.0.0.0:5000 is already in use, using the nearest available port 5001 as an alternative.
  warnings.warn(Warnings.W124.format(host=host, port=start, serve_port=port))
/opt/anaconda3/lib/python3.12/site-packages/spacy/displacy/__init__.py:106: UserWarning: [W011] It looks like you're calling displacy.serve from within a Jupyter notebook or a similar environment. This likely means you're already running a local web server, so there's no need to make displaCy start another one. Instead, you should be able to replace displacy.serve with displacy.render to show the visualization.
  warnings.warn(Warnings.W011)

Using the 'dep' visualizer
Serving on http://0.0.0.0:5001 ...

Shutting down server on port 5001.

In [208]:
displacy.serve(doc,style="ent",auto_select_port=True)

Using the 'ent' visualizer
Serving on http://0.0.0.0:5001 ...

Shutting down server on port 5001.

## Vectorization
1. BOW
2. TF-IDF
## Embeddings
1. word2Vec (CBOW, SKIP-GRAM)
2. GloVe (Co-occurance matrix)

#### BOW

In [215]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import pandas as pd

In [245]:
documents = ["This is NLP NLP session","nlp uses machine learning","NLP uses deep deep learning"]

In [247]:
cv = CountVectorizer(stop_words="english")

In [249]:
cv.fit(documents)

CountVectorizer(stop_words='english')

In [251]:
cv.vocabulary_

{'nlp': 3, 'session': 4, 'uses': 5, 'machine': 2, 'learning': 1, 'deep': 0}

In [278]:
cv.vocabulary

In [253]:
vocab = sorted(cv.vocabulary_.keys())

In [255]:
doc_vector = cv.transform(documents).toarray()

In [257]:
doc_vector

array([[0, 0, 0, 2, 1, 0],
       [0, 1, 1, 1, 0, 1],
       [2, 1, 0, 1, 0, 1]])

In [259]:
df = pd.DataFrame(doc_vector,columns = vocab)

In [261]:
df

   deep  learning  machine  nlp  session  uses
0     0         0        0    2        1     0
1     0         1        1    1        0     1
2     2         1        0    1        0     1

#### TF-IDF

In [264]:
tfidf = TfidfVectorizer(stop_words="english")

In [266]:
tfidf.fit(documents)

TfidfVectorizer(stop_words='english')

In [268]:
vocab = sorted(tfidf.vocabulary_.keys())

In [270]:
doc_vector = tfidf.transform(documents).toarray()

In [272]:
df = pd.DataFrame(doc_vector,columns = vocab)

In [274]:
df

       deep  learning   machine       nlp   session      uses
0  0.000000  0.000000  0.000000  0.763228  0.646129  0.000000
1  0.000000  0.480458  0.631745  0.373119  0.000000  0.480458
2  0.852367  0.324124  0.000000  0.251711  0.000000  0.324124

#### Embeddings

In [ ]:
## Embeddings :: Embeddings in NLP refer to a dense vector representation of words or other textual units (like sentences or documents) 
## in a continuous vector space, where semantically similar words are mapped closer together.
# Popular Embedding Methods
# 	1.	Word2Vec (Google)
# 	•	Trained using Continuous Bag of Words (CBOW) or Skip-gram models.
# 	•	Example: “king - man + woman ≈ queen”
# 	2.	GloVe (Global Vectors by Stanford)
# 	•	Trained on word co-occurrence statistics from a large corpus.
# 	•	Captures both local and global statistical relationships.
# 	3.	FastText (Facebook)
# 	•	Extends Word2Vec by using character n-grams, making it better for rare and morphologically complex words.
# 	4.	BERT (Bidirectional Encoder Representations from Transformers by Google)
# 	•	Contextual embeddings based on transformer architecture.
# 	•	“Apple” can have different embeddings depending on whether it refers to the fruit or the company.
# 	5.	GPT Embeddings (OpenAI)
# 	•	Contextual embeddings useful for complex text understanding and generation tasks.

In [281]:
import gensim

In [283]:
import gensim.downloader as api
w = api.load("word2vec-google-news-300")

In [289]:
w["King"].shape

(300,)

In [291]:
w.similar_by_word("dog")

[('dogs', 0.8680489659309387),
 ('puppy', 0.8106428384780884),
 ('pit_bull', 0.7803961038589478),
 ('pooch', 0.7627376914024353),
 ('cat', 0.7609457969665527),
 ('golden_retriever', 0.7500901818275452),
 ('German_shepherd', 0.7465174198150635),
 ('Rottweiler', 0.7437615394592285),
 ('beagle', 0.7418621778488159),
 ('pup', 0.7406911253929138)]

In [301]:
w.doesnt_match(["cat","tiger","dog","deer"])

'deer'

In [305]:
w.doesnt_match(["dogs","puppy","pit bull","pooch","cat"])

'dogs'

In [325]:
w.doesnt_match(["India","China","Pakistan","Bhutan","Japan","Sri lanka"])

'Japan'

In [309]:
w.doesnt_match(["table","chair","duster","car","man"])

'man'

In [ ]:
# King - man + Woman = Queen

In [313]:
w.most_similar(
    positive = ["King","Woman"],
    negative = ["Man"],
    topn = 1
)

[('Queen', 0.4929387867450714)]

In [315]:
w.most_similar(positive=["Queen","Man"],
    negative=["Woman"],
    topn=1)

[('King', 0.5305259227752686)]